spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
    url: jdbc:postgresql://localhost:5434/carservice
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect